package leetcode389;

/**
 * 
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 * @author liyuncong
 *
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] charOccurTimes = new int[26];
        for(int i = 0; i < t.length(); i++) {
        	charOccurTimes[t.charAt(i) - 'a']++;
        }
        for(int i = 0; i < s.length(); i++) {
        	charOccurTimes[s.charAt(i) - 'a']--;
        }
        char result = 'a';
        for(int i = 0; i < charOccurTimes.length; i++) {
        	if (charOccurTimes[i] == 1) {
				result = (char) (i + 'a');
				break;
			}
        }
        return result;
    }
    
    public static void main(String[] args) {
		FindTheDifference findTheDifference = new FindTheDifference();
		System.out.println(findTheDifference.findTheDifference("abcd", "abcde"));
	}
}
